name: example_dispatch

on: workflow_dispatch

jobs:
  dispatch_config:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          # repository: PardusEidolon/antora-example-site # add build repo later
          event-type: yumi-spec
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'